ALTER TABLE stages ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;
ALTER TABLE stages ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;

CREATE TABLE IF NOT EXISTS festival_info (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    description TEXT
);
